services:
  drupal:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/drupal:/var/www/html # Monter ton répertoire local contenant Drupal
      - drupal_files:/var/www/html/web/sites/default/files
      - ./app/site.conf:/etc/apache2/sites-available/site.conf
    depends_on:
      - db
    env_file:
      - path: ./.env
        required: true
    secrets:
      - db-password
    networks:
      - destroyer-network
    restart: on-failure

  db:
    image: mariadb:11.2.5-jammy
    env_file:
      - path: ./.env
        required: true
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-password
      MARIADB_DATABASE: ${DRUPAL_DB_NAME}
      MARIADB_USER: ${DRUPAL_DB_USER}
      MARIADB_PASSWORD: /run/secrets/drupal-db-password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306" # Exposer MySQL si nécessaire (par exemple pour phpMyAdmin)
    secrets:
      - db-password
    networks:
      - destroyer-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data:
  drupal_files:

secrets:
  db-password:
    file: ./db/db-password
  drupal-db-password:
    file: ./db/drupal-db-password

networks:
  destroyer-network: